Danielh/eng 833 coalesce multiple opsani dev remedies to
opsani/servox pull request #411
Opened 2022-03-16 01:01 UTC by DanielHHowell

2022-03-23 18:04 UTC, linkous8 requested changes
from a cursory glance a couple of items:
* I dont see any automated unit/integration tests added that cover both types of the configuration
* You added a CLI flag for the checks which is good but I thought there was some kind of check configuration section for the servo.yaml. Can we get it added there as well as it may be required for environment variable configuration

2022-03-25 19:27 UTC, DanielHHowell commented
> from a cursory glance a couple of items:
> 
> * I dont see any automated unit/integration tests added that cover both types of the configuration
> * You added a CLI flag for the checks which is good but I thought there was some kind of check configuration section for the servo.yaml. Can we get it added there as well as it may be required for environment variable configuration

@linkous8 I haven't found a check configuration outside of the CLI flag. Also I don't see any tests that cover the flags of the relevant CLI section, will see about adding that. Do you think an integration test running the two variants of checking on say, fiber-http would be good?

2022-03-31 16:05 UTC, linkous8 commented
> @linkous8 I haven't found a check configuration outside of the CLI flag.

Lets go ahead and add a new ChecksConfiguration model for that, say, around here: https://github.com/opsani/servox/blob/d027184c45e0bd2e15724a7a4c9af336602cf57a/servo/configuration.py#L467

Long term, I'm looking to streamline the CLI entrypoint to make the flow more understandable and will be preferring file/env var based configuration over CLI flags as the latter is more difficult to keep track of and alter programmatically

> Also I don't see any tests that cover the flags of the relevant CLI section, will see about adding that. Do you think an integration test running the two variants of checking on say, fiber-http would be good?

See if you can adapt this test to test both variants of the configuration: https://github.com/opsani/servox/blob/d027184c45e0bd2e15724a7a4c9af336602cf57a/tests/connectors/opsani_dev_test.py#L1176

2022-05-03 22:57 UTC, linkous8 approved these changes
A few minor nitpicks aside, LGTM! 🚀

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
> +        check_halting = checks_config.check_halting
These variables are used once each, please reference the config directly for brevity and clarity on lines 791 and 799

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
> +        passing: set,
```suggestion
        results: list[servo.events.EventResult],
        passing: set[str],
```

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
>  import servo.logging
add import for servo.events (note the event reduction may be better located in the servo if events import turns into a circular reference anywhere)

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
> +        )
```suggestion
        checks: list[Check] = functools.reduce(lambda a, b: a + b.value, results, [])
```

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
> +    async def checks_to_table(cls, checks_config, results) -> Tuple[bool, str]:
```suggestion
    async def checks_to_table(cls, checks_config, results) -> str:
```

2022-05-03 22:57 UTC, linkous8 commented on servo/checks.py
> +        if not quiet:
Move this check to line 476 of servo.py. to_table should always return a table

2022-05-04 16:47 UTC, linkous8 commented on servo/servo.py
> +                    print_callback(output)
```suggestion
            if not progressive and not quiet:
                output = await servo.checks.CheckHelpers.checks_to_table(
                    checks_config=self.config.checks, results=results
                )
                print_callback(output)
```

2022-05-04 16:47 UTC, linkous8 commented on servo/servo.py
> +                    print_callback(output)
No need to process table if quiet

2022-05-04 19:05 UTC, merged