Add coverage report + artifact upload to integration and system tests
opsani/servox pull request #425
Opened 2022-04-27 16:16 UTC by DanielHHowell

2022-05-04 21:34 UTC, linkous8 requested changes
@DanielHHowell thanks so much for adding this! Results look good so far!

<img width="2360" alt="image" src="https://user-images.githubusercontent.com/19753981/166829447-b9a6e5bb-0b60-4a50-abf2-47b1cd8ab8fa.png">


However there is a bit of room for improvement https://stackoverflow.com/a/58278633

2022-05-05 20:08 UTC, DanielHHowell commented
@linkous8 that coverage appending looks like a great feature! But it seems this would require having `pytest` run in the same job/env as the unit tests -- do we want to combine those then?

2022-05-05 20:25 UTC, linkous8 commented
> @linkous8 that coverage appending looks like a great feature! But it seems this would require having `pytest` run in the same job/env as the unit tests -- do we want to combine those then?

A very good point. Github provides the artifacts as a means of transferring the environment details between workflow jobs. You should be able to download the report from the unit test artifact to be appended to by the integration tests (note this will likely require we make the integration tests dependent upon the completion of the unit test before they start their run)

2022-05-05 20:31 UTC, linkous8 commented
Also meant to say it should fall back to running standalone if the unit test job fails

2022-05-18 17:56 UTC, blakewatters commented on .github/workflows/test.yaml
> +      # Note: pin to v0.5.7
put it into a var you can reference in one place

2022-05-18 18:00 UTC, blakewatters commented on pyproject.toml
> +coverage = "^6.3.3"
This should be a development dependency not a primary

2022-05-18 18:06 UTC, blakewatters commented
I would strongly advise against making the integration tests dependent upon completion of the units. I made this test suite wicked fast by parallelizing the shit out of it.

What you want to do (and I don't know how to get there but pretty sure its possible) is to add a tail job that waits for the unit/integration reports to be published and then kicks in to combine and report them once they are available.

Serializing the suite is trading off speed that you need day to day for a coverage report that let's be honest you prolly aren't gonna do shit about.

Don't cripple the workflow. Always defend the territory you have already taken and only trade it off explicitly when the upside is just too good to pass off.

2022-07-21 20:46 UTC, merged