Update checks config docs and readme, fix import error in utilities r…
opsani/servox pull request #445
Opened 2022-08-02 20:06 UTC by DanielHHowell

…egex parsing

2022-08-03 21:25 UTC, linkous8 requested changes
https://github.com/opsani/servox/blob/2a21c5e58568e868845664398b1d5146d4d9538f/README.md?plain=1#L98

Update to `servo run --dry-run`

We can also get rid of the Open Questions section now 🙂 https://github.com/opsani/servox/blob/2a21c5e58568e868845664398b1d5146d4d9538f/docs/checks.md?plain=1#L480-L505

2022-08-03 21:25 UTC, linkous8 commented on docs/checks.md
> +opsani-dev:kube-metrics          √ PASSED
```suggestion
CONNECTOR                        STATUS    ERRORS
test.optimizer.com/test          X FAILED  (1/1) Opsani API connectivity: ['Response status code: 404']
opsani_dev                       √ PASSED
opsani-dev:kubernetes            √ PASSED
opsani-dev:prometheus            X FAILED  (1/1) Connect to "http://localhost:9090": ['caught exception (ConnectError): [Errno 61] Connection refused']
opsani-dev:kube-metrics          √ PASSED
```

Add errors to increase documentational coverage

2022-08-03 21:25 UTC, linkous8 commented on docs/checks.md
> +      progressive: True
```suggestion
      progressive: False
```

This seems to be a misnomer that I wish I'd caught sooner but its too late to fix it now. I'll make a mental note to ensure its not carried over in the refactor 🙃 (also it has to be false to get the table)

2022-08-05 17:37 UTC, DanielHHowell commented on docs/checks.md
> +        max: 3.0GiB
I thought about just including the checks config and do so in the examples below, but I thought a 'complete' example would be good to see at the top to visually grasp. I can add a line explaining accordingly, or if you feel strongly about it remove the 'complete' sample yaml per suggestion

2022-08-12 12:50 UTC, linkous8 commented on docs/checks.md
> +    ...
```suggestion
    opsani_dev:
      ...
```

2022-08-12 12:53 UTC, linkous8 approved these changes
Looks good, thanks again for getting this documented 📝 🎉

2022-08-12 13:19 UTC, merged